### ISSUE TITLE
Como colocar tempo de espera entre passos

### ISSUE THREAD

**Issue by Petherson-Erasmo** [thiagodp/concordialang#46]
Olá, gostaríamos de saber se tem como colocar um tempo de espera entre passos ou esperar até que um elemento apareça na tela.

**Comment by Petherson-Erasmo** [comment]
Acabamos de encontrar #22 que tinha um exemplo de como utilizar o que queríamos, só ficamos um pouco surpresos por não encontrarmos menção a essa funcionalidade nessa página aqui: https://github.com/thiagodp/concordialang/blob/master/docs/pt/language.md#Constru%C3%A7%C3%B5es-da-linguagem

**Comment by thiagodp** [comment]
Olá @Tester-dzaine ,

a documentação que você está procurando está na página que lista as [ações suportadas](https://github.com/thiagodp/concordialang/blob/master/docs/pt/actions.md).

Vou colocar um link para essa página, na que você se referiu, para auxiliar. Entretanto, você pode encontrar todos os links da documentação em Português aqui:
https://github.com/thiagodp/concordialang/tree/master/docs/pt

**Comment by Petherson-Erasmo** [comment]
Obrigado @thiagodp

**Comment by thiagodp** [comment]
@Tester-dzaine Aproveitei para atualizar a documentação das ações, acrescentando uma explicação rápida sobre cada uma. Qualquer sugestão de melhoria é sempre bem-vinda! ;)

**Comment by thiagodp** [comment]
@Tester-dzaine Agora a documentação das ações em Português também possui um índice descritivo:
https://github.com/thiagodp/concordialang/blob/master/docs/pt/actions.md

**Comment by Petherson-Erasmo** [comment]
Obrigado @thiagodp
