### ISSUE TITLE
Geração de relatórios em HTML

### ISSUE THREAD

**Issue by Petherson-Erasmo** [thiagodp/concordialang#47]
Bom dia Thiago, segui os passos para instalar a dependência mochawesome, porém a opção timestamp não está salvando novos relatórios para cada geração de teste e a opção autoOpen não abre uma o relatório no navegador.Estou usando o Google Chrome como navegador padrão.

![image](https://user-images.githubusercontent.com/53876624/63168135-af4fec00-c009-11e9-8583-71ded676fd43.png)
![image](https://user-images.githubusercontent.com/53876624/63168182-d4dcf580-c009-11e9-815a-df9b43a42d01.png)

**Comment by thiagodp** [comment]
Olá, @Tester-dzaine,
por gentileza, veja se funciona ao instalar o `mochawesome-report-generator`:
```bash
npm i --save-dev mochawesome-report-generator
```

**Comment by thiagodp** [comment]
@Tester-dzaine Deve funcionar ao instalar ambos.

**Comment by Petherson-Erasmo** [comment]
Boa Tarde @thiagodp infelizmente não funcionou, é sempre substituído o arquivo html 

![image](https://user-images.githubusercontent.com/53876624/63294263-43d37c00-c2a0-11e9-9a17-2c22e8608169.png)
![image](https://user-images.githubusercontent.com/53876624/63294305-58b00f80-c2a0-11e9-8333-cb0cc6bcef7c.png)

**Comment by thiagodp** [comment]
Olá @Tester-dzaine , na [documentação do Mochawesome Report Generator](https://github.com/adamgruber/mochawesome-report-generator) há uma opção [`overwrite`](https://github.com/adamgruber/mochawesome-report-generator#overwrite) que pode ser colocada como `false`, para que ele gere arquivos sem sobrescrever o anterior. Assim, ele gerará os arquivos com um sufixo como `_001.html`, `_002.html` e assim por diante.

Caso queira configurar o arquivo para ter o formato de data e hora, a documentação também indica que o formato do [`timestamp`](https://github.com/adamgruber/mochawesome-report-generator#timestamp) agora espera uma `string`, em vez de um `boolean`, que deve conter o formato de data/hora desejado.

**Portanto, é possível realizar o que você deseja configurando esses parâmetros.**

Como essa configuração já é externa ao Concordia, vou fechar essa tarefa. Fique livre, porém, para comentar aqui se conseguiu realizar o que deseja, seguindo a documentação.
